In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
from pandas_datareader import wb
import pandas as pd

#Indicators: GDP, GDP per capita, access to electricity, population, CO2 emissions
indicators = ["NY.GDP.MKTP.CD", "NY.GDP.PCAP.CD", "EG.ELC.ACCS.ZS", "SP.POP.TOTL", "EN.ATM.CO2E.KT"]

#ISO Code of countries
#Australia, Bhutan, Germany, France, Indonesia, India, Japan, Korea, Netherlands, Nepal, Russia, South Africa 
countries = ["AUS", "BTN", "DEU", "FRA", "IDN", "IND", "JPN", "KOR", "NPL", "NLD", "RUS", "ZAF"]


df = wb.download(country = countries,
                 indicator = indicators,
                 start = 2018, 
                 end = 2018)

df.rename({"NY.GDP.MKTP.CD":"GDP",
           "NY.GDP.PCAP.CD":"GDP per capita",
           "EG.ELC.ACCS.ZS":"Access to electricity",
           "SP.POP.TOTL": "Population",
           "EN.ATM.CO2E.KT": "kt CO2"}, 
         axis = 1, inplace = True)

df.index = df.index.get_level_values(0)

df

SSLError: HTTPSConnectionPool(host='api.worldbank.org', port=443): Max retries exceeded with url: /v2/countries/AUS;BTN;DEU;FRA;IDN;IND;JPN;KOR;NPL;NLD;RUS;ZAF/indicators/NY.GDP.MKTP.CD?date=2018%3A2018&per_page=25000&format=json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

In [3]:
df_target = pd.DataFrame({"countries":["Bhutan", "Germany", "Japan", "Nepal", "Netherlands"]})
df_target

     countries
0       Bhutan
1      Germany
2        Japan
3        Nepal
4  Netherlands

### Step 1: Create empty columns for the desired indicators

In [4]:
df_target["CO2 emissions (tonnes)"] = ""
df_target["Population"] = ""
df_target

     countries CO2 emissions (tonnes) Population
0       Bhutan
1      Germany
2        Japan
3        Nepal
4  Netherlands

### Step 2: Set the column common with ```df``` in ```df_target``` as index

In [5]:
df_target.set_index("countries", inplace = True)
df_target

            CO2 emissions (tonnes) Population
countries
Bhutan
Germany
Japan
Nepal
Netherlands

### Step 3: Mapping

In [6]:
df_target["CO2 emissions (tonnes)"] = df_target.index.map(df["kt CO2"]) * 1000
df_target["Population"] = df_target.index.map(df["Population"])
df_target["t CO2/capita "] = df_target["CO2 emissions (tonnes)"] / df_target["Population"]
df_target

             CO2 emissions (tonnes)  Population  t CO2/capita
countries
Bhutan                      1380000      754396       1.829278
Germany                   709540000    82905782       8.558390
Japan                    1106150000   126529100       8.742258
Nepal                      12030000    28095712       0.428179
Netherlands               151170000    17231624       8.772824

In [12]:
df.columns

Index(['GDP', 'GDP per capita', 'Access to electricity', 'Population',
       'kt CO2'],
      dtype='object')

In [13]:
df.loc[["Australia","Bhutan","Germany"],["kt CO2","Population"]]

           kt CO2  Population
country
Australia  386620    24982688
Bhutan       1380      754396
Germany    709540    82905782