VLOOKUP implementation in Python in three simple steps
https://towardsdatascience.com/vlookup-implementation-in-python-in-three-simple-steps-93b5a290fd72

How to Do a vLookup in Python using pandas
https://www.geeksforgeeks.org/how-to-do-a-vlookup-in-python-using-pandas/

Country codes
https://laendercode.net/en/3-letter-list.html

In [2]:
#!pip install pandas-datareader

Collecting pandas-datareader
  Obtaining dependency information for pandas-datareader from https://files.pythonhosted.org/packages/3f/16/56c9d648b503619ebe96f726b5f642b68e299b34162ed2d6faa9d7966b7d/pandas_datareader-0.10.0-py3-none-any.whl.metadata
  Downloading pandas_datareader-0.10.0-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: lxml in c:\users\hilton.netta\appdata\local\anaconda3\lib\site-packages (from pandas-datareader) (4.9.3)
Requirement already satisfied: pandas>=0.23 in c:\users\hilton.netta\appdata\local\anaconda3\lib\site-packages (from pandas-datareader) (2.2.1)
Requirement already satisfied: requests>=2.19.0 in c:\users\hilton.netta\appdata\local\anaconda3\lib\site-packages (from pandas-datareader) (2.31.0)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\hilton.netta\appdata\local\anaconda3\lib\site-packages (from pandas>=0.23->pandas-datareader) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hilton.netta\appdata\local\anaconda3\lib\site-packages (from pandas>=0.23->pandas-datareader) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\hilton.netta\appdata\local\anaconda3\lib\site-packages (from pandas>=0.23->pandas-datareader) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hilton.netta\appdata\local\anaconda3\lib\site-packages (from pandas>=0.23->pandas-datareader) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hilton.netta\appdata\local\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hilton.netta\appdata\local\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hilton.netta\appdata\local\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hilton.netta\appdata\local\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (2024.2.2)
Requirement already satisfied: six>=1.5 in c:\users\hilton.netta\appdata\local\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas-datareader) (1.16.0)
Downloading pandas_datareader-0.10.0-py3-none-any.whl (109 kB)
   ---------------------------------------- 0.0/109.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/109.5 kB ? eta -:--:--
   --- ------------------------------------ 10.2/109.5 kB ? eta -:--:--
   --- ------------------------------------ 10.2/109.5 kB ? eta -:--:--
   ---------- ---------------------------- 30.7/109.5 kB 325.1 kB/s eta 0:00:01
   ------------------------- ------------- 71.7/109.5 kB 393.8 kB/s eta 0:00:01
   -------------------------------------- 109.5/109.5 kB 576.9 kB/s eta 0:00:00
Installing collected packages: pandas-datareader
Successfully installed pandas-datareader-0.10.0

In [3]:
from pandas_datareader import wb #!pip install pandas-datareader
import pandas as pd

#Indicators: GDP, GDP per capita, access to electricity, population, CO2 emissions
indicators = ["NY.GDP.MKTP.CD", "NY.GDP.PCAP.CD", "EG.ELC.ACCS.ZS",
              "SP.POP.TOTL", "EN.ATM.CO2E.KT"]

#ISO Code of countries: Australia, Bhutan, Germany, France, Indonesia, India, Japan,
#Korea, Netherlands, Nepal, Russia, South Africa 
countries = ["AUS", "BTN", "DEU", "FRA", "IDN", "IND", "JPN",
              "KOR", "NPL", "NLD", "RUS", "ZAF","USA", "GBR", "ZWE", "CHN"]

df = wb.download(country = countries,
                 indicator = indicators,
                 start = 2018, 
                 end = 2018)

df.rename({"NY.GDP.MKTP.CD":"GDP",
           "NY.GDP.PCAP.CD":"GDP per capita",
           "EG.ELC.ACCS.ZS":"Access to electricity",
           "SP.POP.TOTL": "Population",
           "EN.ATM.CO2E.KT": "kt CO2"}, 
         axis = 1, inplace = True)

df.index = df.index.get_level_values(0)

df

C:\Users\hilton.netta\AppData\Local\Temp\ipykernel_31236\30446608.py:14: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = wb.download(country = countries,

,GDP,GDP per capita,Access to electricity,Population,kt CO2
country,,,,,
Australia,1.429734e+12,57273.520475,100.0,24963258,396059.9
Bhutan,2.583336e+09,3389.777303,100.0,762096,1454.3
China,1.389491e+13,9905.406383,100.0,1402760000,10567262.0
France,2.790957e+12,41557.854859,100.0,67158348,306948.4
Germany,3.974443e+12,47939.278288,100.0,82905782,707770.2
India,2.702930e+12,1974.377731,95.7,1369003306,2458175.9
Indonesia,1.042272e+12,3902.661676,98.5,267066843,568007.6
Japan,5.040881e+12,39751.133098,100.0,126811000,1111115.3
"Korea, Rep.",1.725373e+12,33447.156284,100.0,51585058,630186.6
Nepal,3.311153e+10,1161.534352,93.9,28506712,15139.4
Netherlands,9.140434e+11,53044.532435,100.0,17231624,151382.3
Russian Federation,1.657329e+12,11211.887695,100.0,145398106,1661000.0
South Africa,4.052607e+11,7067.724165,84.7,57339635,439644.6
United Kingdom,2.871340e+12,43203.814106,100.0,66460344,360555.9
United States,2.065652e+13,63201.045848,100.0,326838199,4975300.4
Zimbabwe,3.415607e+10,2269.177012,45.4,15052184,11069.9

### Three easy steps to implement it in Python
Herein, I describe the implementation of the same function used in Excel above, but in Python in three simple steps:
First, we create a dataframe called df_target where we want to have the desired subset data. Initially, the dataframe comprises the names of the nine desired countries. And then we create empty columns for the indicators - CO2 emissions (tonnes) and Population, that we want to return from df.

In [4]:
df_target = pd.DataFrame({"countries" : ["Bhutan", "Germany", "Japan", "Nepal", "Netherlands", "South Africa", "United States", "Russian Federation", "China"]})
df_target

            countries
0              Bhutan
1             Germany
2               Japan
3               Nepal
4         Netherlands
5        South Africa
6       United States
7  Russian Federation
8               China

#### Step 1: Create empty columns for the desired indicators

In [5]:
df_target["CO2 Emissions (tonnes)"] = ""
df_target["Population"] = ""
df_target

            countries CO2 Emissions (tonnes) Population
0              Bhutan
1             Germany
2               Japan
3               Nepal
4         Netherlands
5        South Africa
6       United States
7  Russian Federation
8               China

#### Step 2: Set the column common with df in df_target as index

In [6]:
df_target.set_index("countries", inplace = True)
df_target

                   CO2 Emissions (tonnes) Population
countries
Bhutan
Germany
Japan
Nepal
Netherlands
South Africa
United States
Russian Federation
China

#### Step 3: Mapping
This is the main step: we map the index in df_target against df to get the data for required columns as output. For example, the values in kt CO2 column of df multiplied by 1000 is returned for the CO2 emissions (tonnes) column of df_target. The map() function maps the value of Series according to input correspondence and is used for substituting each value in a Series with another value, that could be extracted from a function, a dictionary or a Series.

In [7]:
df_target["CO2 Emissions (tonnes)"] = df_target.index.map(df["kt CO2"]) * 1000
df_target["Population"] = df_target.index.map(df["Population"])
df_target["t CO2/capita"] = df_target["CO2 Emissions (tonnes)"] / df_target["Population"]
df_target

                    CO2 Emissions (tonnes)  Population  t CO2/capita
countries
Bhutan                        1.454300e+06      762096      1.908290
Germany                       7.077702e+08    82905782      8.537043
Japan                         1.111115e+09   126811000      8.761979
Nepal                         1.513940e+07    28506712      0.531082
Netherlands                   1.513823e+08    17231624      8.785144
South Africa                  4.396446e+08    57339635      7.667377
United States                 4.975300e+09   326838199     15.222518
Russian Federation            1.661000e+09   145398106     11.423808
China                         1.056726e+10  1402760000      7.533193