# Monte Carlo Simulation with Python
### Practical Business Python - February 2019

https://pbpython.com/monte-carlo.html

### Introduction
There are many sophisticated models people can build for solving a forecasting problem. However, they frequently stick to simple Excel models based on average historical values, intuition and some high level domain-specific heuristics. This approach may be precise enough for the problem at hand but there are alternatives that can add more information to the prediction with a reasonable amount of additional effort.

One approach that can produce a better understanding of the range of potential outcomes and help avoid the “flaw of averages” is a Monte Carlo simulation. The rest of **this article will describe how to use python with pandas and numpy to build a Monte Carlo simulation to predict the range of potential values for a sales compensation budget**. This approach is meant to be simple enough that it can be used for other problems you might encounter but also powerful enough to provide insights that a basic “gut-feel” model can not provide on its own.

### Problem Background
For this example, we will try to predict how much money we should budget for sales commissions for the next year. This problem is useful for modeling because we have a defined formula for calculating commissions and we likely have some experience with prior years’ commissions payments.

This problem is also important from a business perspective. Sales commissions can be a large selling expense and it is important to plan appropriately for this expense. In addition, the use of a Monte Carlo simulation is a relatively simple improvement that can be made to augment what is normally an unsophisticated estimation process.

In this example, the sample sales commission would look like this for a 5 person sales force:

In this example, the commission is a result of this formula:

Commission Amount = Actual Sales * Commission Rate

The commission rate is based on this Percent To Plan table:

Before we build a model and run the simulation, let’s look at a simple approach for predicting next year’s commission expense.

### Naïve Approach to the Problem
Imagine your task as Amy or Andy analyst is to tell finance how much to budget for sales commissions for next year. One approach might be to assume everyone makes 100% of their target and earns the 4% commission rate. Plugging these values into Excel yields this:

Sample Commissions Calc
Imagine you present this to finance, and they say, “We never have everyone get the same commission rate. We need a more accurate model.”

For round two, you might try a couple of ranges:

Now, you have a little bit more information and go back to finance. This time finance says, “this range is useful but what is your confidence in this range? Also, we need you to do this for a sales force of 500 people and model several different rates to determine the amount to budget.” Hmmm… Now, what do you do?

This simple approach illustrates the basic iterative method for a Monte Carlo simulation. You iterate through this process many times in order to determine a range of potential commission values for the year. Doing this manually by hand is challenging. Fortunately, python makes this approach much simpler.

### Monte Carlo
Now that we have covered the problem at a high level, we can discuss how Monte Carlo analysis might be a useful tool for predicting commissions expenses for the next year. At its simplest level, a Monte Carlo analysis (or simulation) involves running many scenarios with different random inputs and summarizing the distribution of the results.

Using the commissions analysis, we can continue the manual process we started above but run the program 100’s or even 1000’s of times and we will get a distribution of potential commission amounts. This distribution can inform the likelihood that the expense will be within a certain window. At the end of the day, this is a prediction so we will likely never predict it exactly. We can develop a more informed idea about the potential risk of under or over budgeting.

There are two components to running a Monte Carlo simulation:

the equation to evaluate
the random variables for the input
We have already described the equation above. Now we need to think about how to populate the random variables.

One simple approach would be to take a random number between 0% and 200% (representing our intuition about commissions rates). However, because we pay commissions every year, we understand our problem in a little more detail and can use that prior knowledge to build a more accurate model.

Because we have paid out commissions for several years, we can look at a typical historical distribution of percent to target:

### Building a Python Model
We can use pandas to construct a model that replicates the Excel spreadsheet calculation. There are other python approaches to building Monte Carlo models but I find that this pandas method is conceptually easier to comprehend if you are coming from an Excel background. It also has the added benefit of generating pandas dataframes that can be inspected and reviewed for reasonableness.

First complete our imports and set our plotting style:

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

sns.set_style('whitegrid')

For this model, we will use a random number generation from numpy. The handy aspect of numpy is that there are several random number generators that can create random samples based on a predefined distribution.

As described above, we know that our historical percent to target performance is centered around a a mean of 100% and standard deviation of 10%. Let’s define those variables as well as the number of sales reps and simulations we are modeling:

For this model, we will use a random number generation from numpy. The handy aspect of numpy is that there are several random number generators that can create random samples based on a predefined distribution.

As described above, we know that our historical percent to target performance is centered around a a mean of 100% and standard deviation of 10%. Let’s define those variables as well as the number of sales reps and simulations we are modeling:

In [2]:
avg = 1
std_dev = .1
num_reps = 500
num_simulations = 1000

Now we can use numpy to generate a list of percentages that will replicate our historical normal distribution:

In [3]:
pct_to_target = np.random.normal(avg, std_dev, num_reps).round(2)
pct_to_target

array([1.05, 0.96, 0.85, 1.02, 1.02, 1.2 , 1.13, 1.05, 1.17, 0.86, 0.99,
       0.84, 0.88, 0.77, 1.  , 1.05, 0.97, 0.96, 0.92, 0.99, 1.  , 1.06,
       1.08, 0.97, 0.97, 0.93, 1.  , 1.03, 0.99, 1.09, 0.98, 0.94, 1.1 ,
       0.93, 1.05, 0.95, 0.96, 0.95, 1.09, 1.05, 1.  , 0.96, 1.1 , 0.96,
       0.94, 1.  , 0.79, 0.92, 0.84, 0.93, 0.91, 0.92, 1.07, 0.9 , 1.04,
       0.99, 0.96, 1.01, 1.06, 0.98, 0.88, 0.92, 1.02, 1.03, 0.93, 1.07,
       0.91, 0.95, 1.09, 0.87, 0.99, 0.86, 0.9 , 1.05, 1.09, 1.02, 0.78,
       0.92, 0.92, 0.94, 1.07, 1.07, 1.23, 1.01, 0.95, 1.13, 0.99, 1.08,
       1.04, 1.06, 0.88, 0.95, 1.11, 1.  , 1.12, 0.95, 0.92, 0.87, 0.92,
       1.12, 1.16, 1.  , 0.79, 0.83, 0.71, 0.97, 1.04, 1.15, 1.02, 1.1 ,
       1.05, 0.98, 0.88, 1.21, 1.12, 0.88, 1.19, 0.88, 1.02, 1.12, 1.09,
       0.91, 1.01, 1.02, 1.21, 1.08, 1.14, 0.98, 1.01, 0.92, 1.08, 0.99,
       1.05, 1.16, 0.83, 1.05, 1.05, 1.  , 1.1 , 1.04, 0.84, 1.04, 0.89,
       1.04, 1.05, 0.95, 1.03, 1.14, 0.99, 0.78, 0.83, 1.01, 0.94, 1.01,
       1.04, 1.11, 0.84, 1.06, 1.1 , 1.1 , 1.07, 0.86, 1.01, 1.  , 1.11,
       0.8 , 0.93, 0.9 , 1.1 , 1.03, 1.1 , 1.13, 0.87, 1.05, 0.87, 0.93,
       0.84, 0.91, 1.02, 0.92, 0.86, 0.91, 1.01, 1.03, 0.97, 0.96, 0.94,
       0.99, 1.04, 1.04, 0.94, 0.98, 0.87, 1.01, 0.91, 1.13, 0.97, 0.96,
       0.89, 1.01, 1.09, 0.96, 0.95, 0.89, 0.93, 0.98, 1.11, 0.99, 0.98,
       1.1 , 1.  , 0.87, 0.88, 0.89, 0.92, 0.86, 0.99, 0.9 , 0.97, 1.06,
       1.04, 0.88, 1.15, 0.91, 1.15, 0.97, 1.24, 1.11, 1.04, 1.03, 1.02,
       1.09, 0.96, 0.86, 0.96, 0.92, 0.95, 0.91, 0.98, 1.07, 1.15, 0.94,
       0.88, 0.94, 0.97, 1.09, 0.97, 1.11, 0.92, 0.94, 0.89, 0.94, 1.12,
       0.86, 0.68, 1.11, 1.08, 0.97, 1.07, 0.88, 0.97, 1.04, 1.01, 1.06,
       0.94, 1.  , 1.  , 0.78, 0.97, 0.95, 0.93, 1.11, 1.08, 1.09, 0.83,
       1.02, 1.02, 1.02, 1.04, 1.04, 1.16, 0.99, 0.91, 1.02, 0.99, 0.97,
       0.91, 0.91, 1.03, 0.88, 0.91, 1.01, 0.97, 1.07, 1.06, 1.11, 1.18,
       1.08, 0.95, 1.02, 0.92, 0.97, 0.86, 1.  , 0.93, 1.08, 0.98, 0.87,
       1.01, 1.03, 0.96, 0.88, 1.13, 0.84, 1.02, 0.91, 0.97, 0.97, 1.04,
       0.93, 1.12, 0.95, 1.12, 0.99, 1.11, 0.89, 1.04, 1.1 , 1.1 , 0.95,
       0.84, 1.13, 0.88, 1.19, 0.98, 1.27, 0.85, 1.05, 0.99, 0.86, 0.88,
       0.94, 0.97, 0.88, 1.02, 1.05, 1.09, 1.06, 0.85, 1.01, 1.2 , 1.04,
       1.16, 1.02, 1.06, 1.  , 1.16, 0.99, 1.03, 0.94, 0.98, 1.02, 1.17,
       1.  , 0.87, 1.1 , 1.09, 0.96, 1.01, 1.05, 0.92, 1.06, 0.89, 1.  ,
       0.89, 1.07, 0.94, 1.19, 1.05, 0.9 , 1.18, 0.96, 1.04, 1.07, 1.12,
       1.05, 1.2 , 1.05, 0.8 , 1.17, 0.94, 0.99, 0.94, 0.93, 1.07, 0.95,
       0.87, 0.95, 1.03, 0.91, 1.09, 0.86, 0.87, 1.12, 0.99, 1.02, 0.77,
       1.04, 0.88, 0.94, 1.05, 0.93, 1.  , 1.02, 0.91, 1.03, 1.02, 1.07,
       1.02, 0.74, 1.22, 0.98, 1.05, 0.96, 0.87, 0.97, 1.  , 1.06, 1.11,
       1.01, 1.05, 0.98, 1.14, 0.88, 1.25, 1.05, 1.05, 0.93, 1.1 , 1.  ,
       0.99, 1.24, 1.13, 1.1 , 1.3 , 0.92, 1.02, 0.99, 0.95, 0.99, 0.9 ,
       0.73, 1.  , 1.3 , 1.06, 1.  , 0.84, 0.96, 0.95, 1.05, 1.07, 1.04,
       1.  , 1.17, 1.14, 0.98, 0.95, 0.93, 1.14, 1.13, 1.05, 0.89, 1.04,
       1.24, 1.04, 0.9 , 1.03, 1.01, 0.94, 1.02, 1.04, 0.97, 0.92, 1.03,
       0.97, 1.04, 0.88, 1.01, 1.14, 1.12, 1.  , 1.24, 0.89, 0.93, 1.05,
       1.01, 1.01, 1.17, 1.03, 0.91])

For this example, I have chosen to round it to 2 decimal places in order to make it very easy to see the boundaries.

Here is what the first 10 items look like:

array([0.92, 0.98, 1.1 , 0.93, 0.92, 0.99, 1.14, 1.28, 0.91, 1.  ])

This is a good quick check to make sure the ranges are within expectations.

Since we are trying to make an improvement on our simple approach, we are going to stick with a normal distribution for the percent to target. By using numpy though, we can adjust and use other distribution for future models if we must. However, I do warn that you should not use other models without truly understanding them and how they apply to your situation.

There is one other value that we need to simulate and that is the actual sales target. In order to illustrate a different distribution, we are going to assume that our sales target distribution looks something like this:

This is definitely not a normal distribution. This distribution shows us that sales targets are set into 1 of 6 buckets and the frequency gets lower as the amount increases. This distribution could be indicative of a very simple target setting process where individuals are bucketed into certain groups and given targets consistently based on their tenure, territory size or sales pipeline.

For the sake of this example, we will use a uniform distribution but assign lower probability rates for some of the values.

Here is how we can build this using numpy.random.choice

In [4]:
sales_target_values = [75_000, 100_000, 200_000, 300_000, 400_000, 500_000]
sales_target_prob = [.3, .3, .2, .1, .05, .05]
sales_target = np.random.choice(sales_target_values, num_reps, p = sales_target_prob)
sales_target

array([ 75000,  75000, 300000,  75000, 300000, 300000,  75000,  75000,
       200000,  75000,  75000,  75000, 200000,  75000, 400000, 200000,
       100000,  75000,  75000,  75000, 100000, 400000,  75000,  75000,
       400000, 200000, 400000,  75000, 400000, 200000,  75000, 500000,
        75000, 100000,  75000, 100000, 400000, 200000,  75000,  75000,
       200000,  75000, 100000, 100000, 100000, 200000, 100000,  75000,
       200000, 200000, 200000, 200000, 100000,  75000, 100000, 100000,
       100000,  75000, 200000, 200000, 200000, 100000,  75000, 100000,
       100000,  75000, 100000, 100000, 200000,  75000,  75000,  75000,
       200000,  75000, 100000, 200000, 200000, 100000, 200000, 100000,
       500000, 300000, 400000,  75000, 300000, 200000, 100000, 400000,
        75000,  75000, 300000, 500000, 100000, 500000, 400000,  75000,
       500000, 200000,  75000, 100000,  75000, 100000, 300000, 200000,
       300000, 200000, 200000, 200000, 200000, 100000, 200000,  75000,
        75000, 200000, 100000, 200000,  75000, 100000, 100000, 500000,
        75000,  75000,  75000, 300000, 200000, 200000, 500000,  75000,
        75000,  75000,  75000, 200000, 500000,  75000,  75000, 100000,
       300000, 200000, 300000,  75000, 100000, 400000, 100000,  75000,
       300000, 100000,  75000,  75000,  75000, 200000, 100000, 200000,
        75000, 200000,  75000,  75000,  75000,  75000, 200000, 100000,
       100000, 200000,  75000, 400000, 100000,  75000, 100000, 100000,
       100000,  75000,  75000,  75000,  75000,  75000,  75000,  75000,
       100000, 200000,  75000, 200000, 100000, 200000,  75000,  75000,
       400000,  75000, 300000, 100000,  75000,  75000, 100000,  75000,
       200000, 100000, 100000, 200000, 100000, 200000, 100000, 200000,
       100000, 100000, 300000, 100000,  75000, 400000, 400000,  75000,
       200000,  75000, 300000, 100000, 400000,  75000, 300000, 200000,
       100000, 200000, 300000, 300000,  75000,  75000, 100000, 100000,
       500000, 100000, 100000, 100000, 500000, 100000, 200000, 300000,
       200000,  75000, 100000, 200000,  75000,  75000,  75000, 100000,
       100000, 300000,  75000, 200000, 200000,  75000, 100000,  75000,
       100000,  75000, 100000, 500000, 100000, 100000, 200000, 300000,
        75000, 300000,  75000,  75000, 200000, 100000, 200000, 400000,
       200000, 200000, 500000,  75000, 100000,  75000, 100000,  75000,
        75000, 100000, 100000, 500000,  75000, 400000, 200000, 100000,
        75000,  75000, 100000,  75000, 300000,  75000, 300000, 100000,
       100000, 300000,  75000,  75000,  75000, 200000, 100000,  75000,
        75000, 500000, 100000,  75000,  75000, 200000,  75000, 100000,
        75000, 500000,  75000,  75000, 500000, 100000, 100000, 200000,
       100000, 300000, 100000,  75000, 200000, 200000, 400000,  75000,
        75000,  75000, 100000, 400000, 200000,  75000, 100000,  75000,
        75000, 100000,  75000, 200000,  75000, 400000, 300000, 500000,
       300000, 400000,  75000, 100000, 200000, 200000, 200000, 100000,
       300000, 500000,  75000,  75000,  75000, 300000, 100000, 100000,
        75000,  75000, 200000,  75000, 100000, 100000, 200000, 200000,
        75000, 400000, 100000, 100000, 500000, 200000,  75000, 500000,
       100000,  75000, 500000, 100000,  75000, 200000,  75000,  75000,
       200000, 200000, 100000,  75000,  75000,  75000, 100000, 200000,
        75000, 300000, 300000, 100000, 300000, 100000, 100000, 200000,
        75000,  75000, 400000, 500000, 100000, 100000,  75000, 300000,
       300000,  75000, 200000,  75000, 200000,  75000,  75000, 100000,
        75000, 100000, 200000, 100000, 100000, 300000,  75000, 100000,
       100000,  75000, 300000, 100000,  75000,  75000,  75000, 200000,
       100000, 200000,  75000,  75000,  75000,  75000,  75000, 200000,
       200000, 300000, 200000,  75000, 200000,  75000, 400000, 300000,
       200000, 100000,  75000, 400000,  75000, 200000, 200000, 100000,
       300000, 100000, 100000, 200000,  75000,  75000,  75000, 100000,
       100000,  75000, 100000,  75000,  75000, 300000,  75000, 500000,
       400000,  75000, 500000,  75000, 100000, 300000, 100000,  75000,
       500000, 100000, 100000, 300000,  75000, 100000, 300000,  75000,
       200000, 200000, 200000,  75000, 100000, 500000, 400000,  75000,
       100000,  75000, 300000, 200000, 100000, 200000, 500000, 200000,
       400000, 100000,  75000,  75000])

Admittedly this is a somewhat contrived example but I wanted to show how different distributions could be incorporated into our model.

Now that we know how to create our two input distributions, let’s build up a pandas dataframe:

In [5]:
df = pd.DataFrame(index=range(num_reps), data={'Pct_To_Target': pct_to_target,
                                               'Sales_Target': sales_target})

df['Sales'] = df['Pct_To_Target'] * df['Sales_Target']

Here is what our new dataframe looks like:

In [6]:
df

     Pct_To_Target  Sales_Target     Sales
0             1.05         75000   78750.0
1             0.96         75000   72000.0
2             0.85        300000  255000.0
3             1.02         75000   76500.0
4             1.02        300000  306000.0
..             ...           ...       ...
495           1.01        200000  202000.0
496           1.01        400000  404000.0
497           1.17        100000  117000.0
498           1.03         75000   77250.0
499           0.91         75000   68250.0

[500 rows x 3 columns]

You might notice that I did a little trick to calculate the actual sales amount. For this problem, the actual sales amount may change greatly over the years but the performance distribution remains remarkably consistent. Therefore, I’m using the random distributions to generate my inputs and backing into the actual sales.

The final piece of code we need to create is a way to map our Pct_To_Target to the commission rate. Here is the function:

In [7]:
def calc_commission_rate(x):
    """ Return the commission rate based on the table:
    0   - 90%  = 2%
    91  - 99%  = 3%
      >= 100%  = 4%
    """
    if x <= .90:
        return .02
    if x <= .99:
        return .03
    else:
        return .04

The added benefit of using python instead of Excel is that we can create much more complex logic that is easier to understand than if we tried to build a complex nested if statement in Excel.

Now we create our commission rate and multiply it times sales:

In [8]:
df['Commission_Rate'] = df['Pct_To_Target'].apply(calc_commission_rate)
df['Commission_Amount'] = df['Commission_Rate'] * df['Sales']

Which yields this result, which looks very much like an Excel model we might build:

In [9]:
df

     Pct_To_Target  Sales_Target     Sales  Commission_Rate  Commission_Amount
0             1.05         75000   78750.0             0.04             3150.0
1             0.96         75000   72000.0             0.03             2160.0
2             0.85        300000  255000.0             0.02             5100.0
3             1.02         75000   76500.0             0.04             3060.0
4             1.02        300000  306000.0             0.04            12240.0
..             ...           ...       ...              ...                ...
495           1.01        200000  202000.0             0.04             8080.0
496           1.01        400000  404000.0             0.04            16160.0
497           1.17        100000  117000.0             0.04             4680.0
498           1.03         75000   77250.0             0.04             3090.0
499           0.91         75000   68250.0             0.03             2047.5

[500 rows x 5 columns]

In [10]:
k = df.loc[0:5,['Commission_Amount']].sum(axis = 0)[0]
# https://www.geeksforgeeks.org/how-to-sum-values-of-pandas-dataframe-by-rows/
k

C:\Users\hilton.netta\AppData\Local\Temp\ipykernel_3096\1168147185.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  k = df.loc[0:5,['Commission_Amount']].sum(axis = 0)[0]

40110.0

There you have it!

We have replicated a model that is similar to what we would have done in Excel but we used some more sophisticated distributions than just throwing a bunch of random number inputs into the problem.

In [11]:
print(f'If we sum up the values (only the top 5 are shown above) in the Commission_Amount column, we can see that \
this simulation shows that we would pay {df.loc[0:5,["Commission_Amount"]].sum(axis = 0)[0]}')

If we sum up the values (only the top 5 are shown above) in the Commission_Amount column, we can see that this simulation shows that we would pay 40110.0

C:\Users\hilton.netta\AppData\Local\Temp\ipykernel_3096\3829305155.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  this simulation shows that we would pay {df.loc[0:5,["Commission_Amount"]].sum(axis = 0)[0]}')

### Let’s Loop
The real “magic” of the Monte Carlo simulation is that if we run a simulation many times, we start to develop a picture of the likely distribution of results. In Excel, you would need VBA or another plugin to run multiple iterations. In python, we can use a for loop to run as many simulations as we’d like.

In addition to running each simulation, we save the results we care about in a list that we will turn into a dataframe for further analysis of the distribution of results.

Here is the full for loop code:

In [12]:
# Define a list to keep all the results from each simulation that we want to analyze
all_stats = []

# Loop through many simulations
for i in range(num_simulations):

    # Choose random inputs for the sales targets and percent to target
    sales_target = np.random.choice(sales_target_values, num_reps, p=sales_target_prob)
    pct_to_target = np.random.normal(avg, std_dev, num_reps).round(2)

    # Build the dataframe based on the inputs and number of reps
    df = pd.DataFrame(index=range(num_reps), data={'Pct_To_Target': pct_to_target,
                                                   'Sales_Target': sales_target})

    # Back into the sales number using the percent to target rate
    df['Sales'] = df['Pct_To_Target'] * df['Sales_Target']

    # Determine the commissions rate and calculate it
    df['Commission_Rate'] = df['Pct_To_Target'].apply(calc_commission_rate)
    df['Commission_Amount'] = df['Commission_Rate'] * df['Sales']

    # We want to track sales,commission amounts and sales targets over all the simulations
    all_stats.append([df['Sales'].sum().round(0),
                      df['Commission_Amount'].sum().round(0),
                      df['Sales_Target'].sum().round(0)])

In [71]:
all_stats

[[84764750.0, 2899102.0, 84500000],
 [82975500.0, 2841912.0, 83100000],
 [81780500.0, 2841575.0, 81450000],
 [82893750.0, 2813985.0, 83075000],
 [84630750.0, 2946678.0, 84375000],
 [82019750.0, 2853730.0, 81550000],
 [79091250.0, 2668690.0, 79250000],
 [89202000.0, 3011440.0, 89850000],
 [85789250.0, 2911308.0, 85825000],
 [85820250.0, 2917978.0, 86250000],
 [81177250.0, 2803790.0, 80825000],
 [84411750.0, 2889620.0, 84575000],
 [82181000.0, 2787092.0, 82525000],
 [80927500.0, 2722652.0, 81275000],
 [84876750.0, 2855262.0, 85350000],
 [79010000.0, 2721455.0, 79000000],
 [85592000.0, 2893292.0, 85850000],
 [82156000.0, 2809948.0, 81900000],
 [88197500.0, 3055768.0, 87225000],
 [83538500.0, 2910402.0, 82900000],
 [79869250.0, 2717348.0, 79475000],
 [87622250.0, 3049500.0, 86875000],
 [82758500.0, 2789068.0, 82950000],
 [85244000.0, 2906530.0, 85375000],
 [79195500.0, 2675618.0, 79550000],
 [83024750.0, 2828058.0, 83325000],
 [84383750.0, 2927672.0, 83700000],
 [84666000.0, 2865788.0, 85025000],
 [83941250.0, 2785152.0, 85000000],
 [84359500.0, 2894202.0, 84100000],
 [83959500.0, 2824080.0, 84025000],
 [88886000.0, 3067065.0, 88825000],
 [87073000.0, 2972465.0, 87075000],
 [82302500.0, 2823825.0, 81850000],
 [84166000.0, 2920795.0, 83525000],
 [84301500.0, 2893278.0, 84000000],
 [80968000.0, 2713962.0, 81850000],
 [85216500.0, 2904495.0, 85100000],
 [83621000.0, 2862952.0, 83625000],
 [82509000.0, 2819412.0, 82475000],
 [80258750.0, 2756272.0, 79925000],
 [82822500.0, 2832115.0, 82700000],
 [83278250.0, 2753308.0, 84325000],
 [83153250.0, 2776255.0, 84050000],
 [83993250.0, 2871310.0, 84050000],
 [84722250.0, 2867428.0, 85275000],
 [80053500.0, 2784160.0, 79375000],
 [87630250.0, 3034445.0, 86875000],
 [87434250.0, 2977532.0, 87350000],
 [79450500.0, 2681222.0, 79775000],
 [78312500.0, 2678118.0, 78600000],
 [78980250.0, 2669068.0, 79125000],
 [82304000.0, 2780760.0, 82600000],
 [84601500.0, 2888172.0, 84450000],
 [84993250.0, 2953480.0, 84550000],
 [84481750.0, 2920902.0, 84275000],
 [83991500.0, 2911762.0, 83400000],
 [80077750.0, 2733875.0, 80025000],
 [81320250.0, 2714998.0, 82175000],
 [89931750.0, 3076242.0, 89975000],
 [83510250.0, 2846358.0, 83400000],
 [81911250.0, 2851888.0, 81200000],
 [81719000.0, 2790022.0, 81800000],
 [78765500.0, 2686278.0, 79100000],
 [89722500.0, 3017408.0, 90800000],
 [87086750.0, 2960798.0, 87100000],
 [85452750.0, 2937158.0, 85450000],
 [85257250.0, 2908278.0, 85275000],
 [82512500.0, 2805730.0, 82850000],
 [85205250.0, 2900005.0, 85475000],
 [86824500.0, 2940448.0, 86900000],
 [85674750.0, 2929920.0, 85375000],
 [84369250.0, 2877595.0, 84700000],
 [85948250.0, 2983212.0, 85350000],
 [87131500.0, 2981488.0, 87350000],
 [84254750.0, 2916420.0, 83700000],
 [82227000.0, 2772078.0, 82800000],
 [76943500.0, 2639345.0, 76800000],
 [87066250.0, 3018798.0, 86600000],
 [80900500.0, 2753632.0, 81225000],
 [80423500.0, 2724130.0, 80700000],
 [81074500.0, 2691682.0, 82175000],
 [86477250.0, 2958718.0, 86450000],
 [82457250.0, 2838082.0, 82550000],
 [84535750.0, 2908660.0, 84375000],
 [83392500.0, 2910615.0, 82225000],
 [80349250.0, 2782008.0, 79825000],
 [82603500.0, 2831545.0, 82375000],
 [80460250.0, 2768358.0, 80550000],
 [84940250.0, 2900365.0, 85075000],
 [86336250.0, 2920412.0, 86950000],
 [81765750.0, 2812128.0, 81600000],
 [84447750.0, 2933098.0, 83925000],
 [81711250.0, 2756328.0, 82075000],
 [87053750.0, 2915272.0, 87875000],
 [83906500.0, 2848528.0, 84050000],
 [84933250.0, 2903865.0, 84700000],
 [84021000.0, 2890285.0, 83175000],
 [84163750.0, 2918980.0, 83725000],
 [79389000.0, 2700092.0, 79900000],
 [79882750.0, 2732002.0, 79800000],
 [85814250.0, 2940285.0, 85300000],
 [85886000.0, 2972598.0, 85525000],
 [83348500.0, 2821205.0, 83625000],
 [83305250.0, 2839275.0, 83075000],
 [85112000.0, 2858570.0, 85675000],
 [85359250.0, 2941165.0, 85175000],
 [82559750.0, 2839230.0, 82325000],
 [79184500.0, 2717680.0, 79300000],
 [84375750.0, 2869465.0, 84750000],
 [84524500.0, 2912728.0, 84250000],
 [81130750.0, 2719800.0, 81950000],
 [85057750.0, 2838968.0, 85675000],
 [82408000.0, 2794675.0, 82675000],
 [86176750.0, 3013140.0, 85200000],
 [81849750.0, 2809580.0, 81350000],
 [86153000.0, 2924750.0, 86475000],
 [81588250.0, 2795515.0, 81400000],
 [84830000.0, 2876662.0, 84850000],
 [79755000.0, 2651198.0, 80800000],
 [88230000.0, 3020645.0, 88725000],
 [83067750.0, 2855500.0, 82525000],
 [87160750.0, 2968045.0, 87300000],
 [81629250.0, 2808252.0, 81650000],
 [87807250.0, 2967088.0, 88425000],
 [80325750.0, 2769485.0, 80075000],
 [86973250.0, 2951715.0, 87300000],
 [86559750.0, 2929080.0, 86675000],
 [83067750.0, 2814918.0, 83800000],
 [85505750.0, 2949148.0, 85450000],
 [86567750.0, 2961238.0, 86325000],
 [82788000.0, 2863155.0, 82425000],
 [86847000.0, 2981622.0, 86300000],
 [78822250.0, 2638555.0, 79875000],
 [80331250.0, 2705422.0, 80975000],
 [80836500.0, 2758312.0, 80675000],
 [83559250.0, 2878002.0, 83050000],
 [82466000.0, 2804120.0, 82575000],
 [80835000.0, 2797075.0, 80575000],
 [88941750.0, 3017178.0, 89075000],
 [87941000.0, 3061870.0, 86950000],
 [80929750.0, 2766305.0, 81150000],
 [83529750.0, 2850705.0, 83675000],
 [85302000.0, 2954898.0, 85025000],
 [82262750.0, 2754575.0, 82600000],
 [85143750.0, 2901395.0, 85025000],
 [81060250.0, 2753042.0, 81275000],
 [81565250.0, 2786900.0, 81450000],
 [83932750.0, 2833940.0, 84650000],
 [79765250.0, 2719672.0, 80150000],
 [84273250.0, 2865922.0, 84475000],
 [83755000.0, 2869848.0, 83775000],
 [85853750.0, 2936880.0, 85400000],
 [83014500.0, 2868638.0, 82675000],
 [89580250.0, 3051812.0, 89350000],
 [82875500.0, 2859258.0, 82725000],
 [77180250.0, 2573350.0, 78125000],
 [84982500.0, 2875020.0, 85100000],
 [85391000.0, 2882498.0, 86000000],
 [84605750.0, 2941042.0, 83950000],
 [84850750.0, 2867832.0, 85500000],
 [88242250.0, 3023558.0, 88025000],
 [83166500.0, 2863992.0, 83100000],
 [83111250.0, 2864702.0, 82700000],
 [83282250.0, 2886580.0, 82200000],
 [82709250.0, 2833558.0, 82825000],
 [78419500.0, 2669468.0, 78575000],
 [84046750.0, 2867280.0, 84025000],
 [81497000.0, 2773085.0, 81750000],
 [83404000.0, 2872648.0, 83575000],
 [86406500.0, 2946565.0, 86550000],
 [87849750.0, 2995530.0, 87550000],
 [85221750.0, 2867452.0, 85950000],
 [84395250.0, 2860202.0, 84725000],
 [80315750.0, 2704032.0, 81025000],
 [82461750.0, 2770520.0, 82925000],
 [85898250.0, 2922712.0, 86050000],
 [88049250.0, 3011785.0, 87850000],
 [84479750.0, 2867560.0, 84425000],
 [84354250.0, 2912168.0, 84125000],
 [86254250.0, 2973772.0, 86175000],
 [87252750.0, 2977620.0, 87475000],
 [80603500.0, 2734848.0, 80850000],
 [82292500.0, 2770215.0, 82525000],
 [80218250.0, 2738405.0, 80225000],
 [82987750.0, 2825400.0, 82925000],
 [83274500.0, 2837605.0, 83375000],
 [84784500.0, 2937248.0, 84150000],
 [83743000.0, 2835352.0, 84075000],
 [81177500.0, 2731440.0, 81875000],
 [85053500.0, 2899488.0, 85100000],
 [88528000.0, 3054810.0, 88050000],
 [78407250.0, 2643740.0, 78775000],
 [85177250.0, 2997532.0, 84500000],
 [84272000.0, 2892850.0, 83925000],
 [85264500.0, 2912758.0, 84925000],
 [81029000.0, 2824508.0, 80200000],
 [89297000.0, 3051112.0, 89125000],
 [81374250.0, 2729295.0, 81950000],
 [86075000.0, 2960745.0, 85925000],
 [80866250.0, 2733365.0, 81050000],
 [85125750.0, 2916048.0, 84750000],
 [83439000.0, 2851495.0, 83325000],
 [81892250.0, 2782842.0, 82100000],
 [83052500.0, 2811660.0, 83125000],
 [85834000.0, 2985935.0, 85325000],
 [83163250.0, 2816395.0, 83475000],
 [86734000.0, 2891015.0, 87500000],
 [81260250.0, 2751010.0, 81400000],
 [84404000.0, 2929068.0, 83900000],
 [81233000.0, 2788562.0, 80925000],
 [84069500.0, 2905738.0, 83625000],
 [82267500.0, 2760008.0, 82950000],
 [81737250.0, 2794858.0, 81800000],
 [84387750.0, 2930645.0, 83975000],
 [81960250.0, 2801785.0, 82250000],
 [87805750.0, 3022385.0, 87400000],
 [86657500.0, 2944855.0, 86825000],
 [81029500.0, 2717335.0, 81700000],
 [84292500.0, 2864845.0, 84325000],
 [83743750.0, 2817582.0, 84300000],
 [86745500.0, 2968802.0, 86500000],
 [89781000.0, 3050790.0, 89725000],
 [83633750.0, 2866345.0, 83275000],
 [84537250.0, 2924780.0, 84025000],
 [84185500.0, 2830445.0, 84650000],
 [87671750.0, 3000172.0, 87575000],
 [80085000.0, 2710438.0, 80425000],
 [83682000.0, 2824230.0, 84025000],
 [80477500.0, 2706688.0, 81075000],
 [83700750.0, 2816065.0, 84025000],
 [84444000.0, 2867715.0, 84425000],
 [82218750.0, 2831035.0, 81525000],
 [87222500.0, 2989832.0, 86875000],
 [81973000.0, 2830075.0, 81975000],
 [84952250.0, 2866022.0, 85200000],
 [81598000.0, 2779092.0, 81525000],
 [87604250.0, 2981542.0, 87500000],
 [83310750.0, 2880765.0, 82375000],
 [83983250.0, 2803435.0, 84725000],
 [86993000.0, 3034335.0, 86200000],
 [82042000.0, 2826468.0, 81575000],
 [80837000.0, 2766785.0, 80625000],
 [83420250.0, 2839960.0, 83775000],
 [83740000.0, 2904582.0, 83425000],
 [83710750.0, 2833885.0, 84450000],
 [79724000.0, 2663252.0, 80375000],
 [83626000.0, 2874910.0, 83650000],
 [84376750.0, 2932892.0, 83725000],
 [81298000.0, 2775708.0, 81250000],
 [81705250.0, 2820192.0, 81600000],
 [83727000.0, 2807862.0, 84100000],
 [81739500.0, 2776610.0, 82025000],
 [79516500.0, 2617400.0, 80825000],
 [80440000.0, 2790068.0, 79775000],
 [83794500.0, 2896985.0, 83750000],
 [85554000.0, 2902122.0, 85825000],
 [84201500.0, 2939950.0, 83000000],
 [86600000.0, 2910882.0, 87100000],
 [81811250.0, 2830572.0, 81300000],
 [82538000.0, 2829550.0, 82400000],
 [86532000.0, 2992462.0, 86025000],
 [85858500.0, 2985968.0, 84775000],
 [84810000.0, 2912765.0, 84550000],
 [80945500.0, 2736670.0, 81450000],
 [85416750.0, 2947310.0, 85225000],
 [80731500.0, 2733210.0, 80900000],
 [84758000.0, 2909988.0, 84450000],
 [83954500.0, 2889122.0, 83975000],
 [81621000.0, 2744260.0, 82025000],
 [79348750.0, 2738305.0, 78875000],
 [84058250.0, 2965585.0, 82600000],
 [84678000.0, 2943550.0, 83800000],
 [86078500.0, 2948090.0, 86000000],
 [82931750.0, 2818940.0, 83325000],
 [87161000.0, 2891205.0, 87750000],
 [87609500.0, 2998685.0, 87625000],
 [83045250.0, 2806915.0, 83675000],
 [85214250.0, 2940975.0, 84875000],
 [79919750.0, 2747265.0, 79900000],
 [83223750.0, 2790242.0, 84050000],
 [83831500.0, 2869802.0, 83800000],
 [80571000.0, 2746640.0, 80225000],
 [85948000.0, 2910955.0, 86250000],
 [82314500.0, 2790525.0, 82950000],
 [83207500.0, 2889998.0, 82475000],
 [81707250.0, 2765120.0, 82175000],
 [86770000.0, 2957000.0, 87000000],
 [80914750.0, 2727312.0, 81550000],
 [85272750.0, 2875675.0, 85850000],
 [81142750.0, 2744065.0, 81600000],
 [82079750.0, 2772225.0, 82575000],
 [84202750.0, 2896548.0, 83725000],
 [85856750.0, 2943522.0, 85825000],
 [79414750.0, 2729670.0, 79225000],
 [80127000.0, 2701372.0, 80125000],
 [88939000.0, 3009318.0, 89150000],
 [80987500.0, 2700228.0, 81550000],
 [84382250.0, 2887508.0, 84575000],
 [78001250.0, 2695165.0, 77675000],
 [85677250.0, 2953655.0, 84800000],
 [86663250.0, 2953828.0, 86375000],
 [80602000.0, 2758685.0, 80400000],
 [83264250.0, 2823812.0, 83700000],
 [81061500.0, 2753925.0, 81000000],
 [84692500.0, 2881178.0, 84650000],
 [78324500.0, 2680920.0, 78450000],
 [79791750.0, 2702908.0, 79825000],
 [82576500.0, 2863065.0, 82150000],
 [81654500.0, 2805100.0, 81100000],
 [87677000.0, 3028972.0, 87575000],
 [81645250.0, 2775882.0, 81900000],
 [82598000.0, 2850490.0, 82225000],
 [83599500.0, 2837480.0, 84100000],
 [85112000.0, 2980672.0, 84175000],
 [83199250.0, 2850398.0, 83275000],
 [80573250.0, 2746702.0, 80450000],
 [82160500.0, 2833160.0, 81600000],
 [85549250.0, 2882912.0, 86175000],
 [80974000.0, 2762552.0, 81300000],
 [85147000.0, 2888018.0, 85025000],
 [83644750.0, 2850982.0, 83775000],
 [86071500.0, 2969908.0, 85550000],
 [86666000.0, 2995030.0, 86425000],
 [86609750.0, 2976065.0, 86225000],
 [83955250.0, 2902452.0, 83450000],
 [86532000.0, 2987810.0, 86050000],
 [82615500.0, 2781262.0, 83075000],
 [81118750.0, 2728415.0, 81750000],
 [82574250.0, 2813615.0, 82550000],
 [86764750.0, 2957398.0, 86350000],
 [83738250.0, 2817545.0, 84425000],
 [84283750.0, 2865728.0, 84575000],
 [82120500.0, 2823110.0, 81925000],
 [82917000.0, 2794618.0, 83400000],
 [83210500.0, 2834000.0, 83500000],
 [82313250.0, 2879580.0, 81225000],
 [85242250.0, 2900882.0, 85675000],
 [80259500.0, 2743782.0, 79550000],
 [87110000.0, 2964435.0, 87300000],
 [88757500.0, 3063945.0, 88050000],
 [84294750.0, 2895162.0, 84175000],
 [85467000.0, 2877545.0, 85925000],
 [78998250.0, 2686200.0, 79550000],
 [85346250.0, 2910942.0, 84975000],
 [82518250.0, 2852278.0, 82250000],
 [85571000.0, 2902595.0, 85775000],
 [87459250.0, 2983360.0, 87850000],
 [82471500.0, 2792092.0, 82750000],
 [81310250.0, 2787778.0, 80875000],
 [79096500.0, 2668225.0, 79475000],
 [82828750.0, 2760562.0, 83425000],
 [79954750.0, 2728018.0, 79700000],
 [84465000.0, 2895748.0, 83950000],
 [87983250.0, 2993575.0, 88225000],
 [82088750.0, 2823208.0, 81700000],
 [85963250.0, 2919308.0, 86175000],
 [84302750.0, 2884230.0, 84275000],
 [78934000.0, 2667248.0, 79550000],
 [83430000.0, 2857302.0, 83650000],
 [79605000.0, 2712810.0, 79400000],
 [84648750.0, 2902160.0, 84425000],
 [88354250.0, 3046520.0, 87850000],
 [83090000.0, 2829080.0, 83000000],
 [87701000.0, 3044020.0, 86900000],
 [81698750.0, 2772355.0, 82450000],
 [82061750.0, 2863225.0, 81075000],
 [84504250.0, 2873592.0, 84825000],
 [85929000.0, 2935722.0, 85700000],
 [87369000.0, 3042610.0, 86625000],
 [82945500.0, 2793842.0, 83375000],
 [85257750.0, 2932705.0, 84975000],
 [80400250.0, 2751590.0, 80375000],
 [81314500.0, 2753230.0, 81400000],
 [80124250.0, 2760022.0, 79675000],
 [81894500.0, 2750102.0, 82625000],
 [86616750.0, 2957622.0, 86625000],
 [79404750.0, 2706912.0, 79875000],
 [77592500.0, 2613380.0, 77975000],
 [83366500.0, 2859895.0, 83200000],
 [81773000.0, 2755445.0, 82200000],
 [81377750.0, 2771548.0, 81300000],
 [84155250.0, 2851552.0, 84625000],
 [81593000.0, 2824452.0, 80925000],
 [80126500.0, 2773710.0, 80000000],
 [84541500.0, 2936392.0, 83775000],
 [85309750.0, 2939005.0, 85275000],
 [85454000.0, 2929435.0, 85300000],
 [83909500.0, 2837400.0, 83950000],
 [83616250.0, 2847188.0, 83675000],
 [82863000.0, 2824532.0, 82600000],
 [82767000.0, 2767625.0, 83525000],
 [84986750.0, 2898595.0, 84975000],
 [88880750.0, 2983105.0, 89475000],
 [87825000.0, 3053225.0, 87400000],
 [84326000.0, 2949265.0, 83800000],
 [86223750.0, 2951078.0, 86075000],
 [84348000.0, 2836968.0, 84750000],
 [88905500.0, 3059945.0, 88625000],
 [84328250.0, 2893600.0, 84175000],
 [86389500.0, 2963208.0, 86575000],
 [88239750.0, 3027602.0, 88125000],
 [83288000.0, 2844652.0, 83275000],
 [87955000.0, 3061108.0, 87400000],
 [82107250.0, 2782175.0, 82375000],
 [82570000.0, 2792000.0, 82775000],
 [82477250.0, 2778992.0, 83050000],
 [82846250.0, 2871590.0, 82275000],
 [87973500.0, 3024280.0, 87975000],
 [85862500.0, 2977920.0, 85250000],
 [86022500.0, 2949978.0, 85700000],
 [82859500.0, 2784618.0, 83700000],
 [84855000.0, 2919185.0, 84675000],
 [77949000.0, 2639898.0, 78150000],
 [85858000.0, 2945078.0, 85975000],
 [81783250.0, 2874328.0, 80375000],
 [88522750.0, 3031972.0, 88525000],
 [79111000.0, 2734320.0, 78275000],
 [87955250.0, 3003838.0, 88100000],
 [83649750.0, 2833502.0, 83875000],
 [80416500.0, 2707480.0, 80650000],
 [87635500.0, 2973135.0, 87825000],
 [85316000.0, 2849325.0, 86250000],
 [84080000.0, 2890058.0, 83925000],
 [89311750.0, 3016908.0, 89500000],
 [85982000.0, 2984110.0, 85775000],
 [82505500.0, 2804288.0, 82900000],
 [85141000.0, 2930675.0, 85050000],
 [82486000.0, 2830192.0, 82300000],
 [81658500.0, 2794515.0, 81600000],
 [81773250.0, 2778588.0, 81800000],
 [85187500.0, 2835160.0, 85950000],
 [83481000.0, 2807548.0, 84050000],
 [83891250.0, 2885652.0, 83725000],
 [84274250.0, 2870958.0, 84475000],
 [83753000.0, 2834345.0, 83800000],
 [83419000.0, 2816578.0, 83800000],
 [86671750.0, 2997320.0, 85850000],
 [84397250.0, 2889998.0, 84900000],
 [83909500.0, 2839648.0, 84950000],
 [82084250.0, 2836745.0, 81225000],
 [84323000.0, 2875110.0, 84275000],
 [79881000.0, 2729022.0, 80300000],
 [82735250.0, 2803320.0, 83150000],
 [84331750.0, 2904105.0, 83950000],
 [84804500.0, 2872772.0, 85050000],
 [82387500.0, 2822148.0, 81925000],
 [85218000.0, 2929938.0, 84800000],
 [86400000.0, 2934848.0, 86425000],
 [84150250.0, 2886900.0, 83875000],
 [83662000.0, 2855910.0, 83775000],
 [84321000.0, 2858942.0, 84350000],
 [83056500.0, 2764632.0, 84050000],
 [87323500.0, 2957988.0, 87650000],
 [87216500.0, 2955095.0, 87150000],
 [87337250.0, 2932425.0, 87775000],
 [83892250.0, 2872265.0, 83950000],
 [82464750.0, 2881228.0, 82300000],
 [82809250.0, 2854682.0, 82725000],
 [83082750.0, 2828338.0, 83075000],
 [86435500.0, 2972715.0, 86450000],
 [87838250.0, 3027805.0, 87725000],
 [84797500.0, 2848418.0, 85300000],
 [80835000.0, 2741142.0, 80900000],
 [83584750.0, 2842715.0, 83650000],
 [84897000.0, 2918868.0, 84375000],
 [85983000.0, 2862682.0, 86650000],
 [85945000.0, 2884615.0, 86675000],
 [80843250.0, 2794510.0, 80225000],
 [84110750.0, 2828372.0, 84650000],
 [82509250.0, 2881405.0, 81875000],
 [82587750.0, 2855748.0, 81925000],
 [84567500.0, 2945465.0, 83750000],
 [81499250.0, 2822655.0, 81275000],
 [80995000.0, 2731295.0, 81400000],
 [85235750.0, 2938505.0, 84800000],
 [80349250.0, 2716150.0, 80800000],
 [88284500.0, 3033105.0, 87800000],
 [81183250.0, 2729088.0, 82100000],
 [80290250.0, 2781082.0, 79600000],
 [82970750.0, 2851805.0, 82825000],
 [85863500.0, 3021398.0, 84750000],
 [79389000.0, 2709072.0, 79150000],
 [82655000.0, 2828080.0, 82175000],
 [84740750.0, 2842060.0, 85125000],
 [85320000.0, 2909048.0, 85500000],
 [83389750.0, 2907040.0, 82875000],
 [84218250.0, 2873115.0, 84275000],
 [84068750.0, 2873515.0, 83750000],
 [80240500.0, 2710150.0, 80750000],
 [84913000.0, 2861892.0, 85775000],
 [84362000.0, 2924295.0, 83725000],
 [80967500.0, 2756095.0, 81375000],
 [84447000.0, 2850500.0, 85100000],
 [84692750.0, 2893408.0, 85000000],
 [82845500.0, 2893130.0, 82200000],
 [82588000.0, 2771882.0, 83100000],
 [87142500.0, 2970198.0, 86925000],
 [75133250.0, 2565772.0, 75350000],
 [89677750.0, 3057042.0, 89500000],
 [84903750.0, 2918432.0, 84675000],
 [85978250.0, 2968282.0, 85525000],
 [77094750.0, 2585775.0, 77875000],
 [85140750.0, 2959182.0, 84750000],
 [82230500.0, 2788832.0, 82600000],
 [82646750.0, 2844248.0, 82050000],
 [81439250.0, 2772010.0, 81400000],
 [84567000.0, 2884822.0, 85000000],
 [85717750.0, 2876158.0, 86625000],
 [83662750.0, 2825778.0, 84000000],
 [86325500.0, 2946980.0, 86525000],
 [84033000.0, 2855582.0, 84350000],
 [80913000.0, 2711305.0, 81525000],
 [85191750.0, 2893338.0, 85325000],
 [83812750.0, 2893070.0, 83275000],
 [85026250.0, 2909088.0, 85400000],
 [79132000.0, 2746215.0, 78350000],
 [79973500.0, 2748922.0, 79900000],
 [80678000.0, 2739402.0, 81125000],
 [80127500.0, 2729345.0, 80350000],
 [82781500.0, 2874868.0, 82050000],
 [83292500.0, 2824752.0, 83550000],
 [84567250.0, 2932192.0, 83700000],
 [79137500.0, 2685180.0, 79125000],
 [80808000.0, 2779110.0, 80450000],
 [87442250.0, 2954740.0, 87800000],
 [84478750.0, 2836838.0, 85250000],
 [82344500.0, 2820852.0, 82100000],
 [89055250.0, 3083550.0, 88375000],
 [85952250.0, 2996635.0, 85150000],
 [84233500.0, 2894585.0, 84375000],
 [82814000.0, 2837942.0, 82875000],
 [86243000.0, 2954290.0, 86375000],
 [83562000.0, 2879180.0, 83075000],
 [83884750.0, 2846735.0, 84175000],
 [82417250.0, 2768365.0, 83150000],
 [84312500.0, 2879442.0, 84475000],
 [87973500.0, 3077358.0, 86900000],
 [82223000.0, 2864240.0, 81500000],
 [85898750.0, 2912900.0, 86100000],
 [79218750.0, 2670535.0, 79625000],
 [84802500.0, 2916615.0, 84600000],
 [83937750.0, 2847025.0, 84450000],
 [85798500.0, 2939120.0, 85500000],
 [84156750.0, 2868895.0, 84225000],
 [80187250.0, 2777335.0, 79950000],
 [87169750.0, 3007188.0, 87000000],
 [84617500.0, 2892220.0, 85025000],
 [86900500.0, 3001498.0, 86500000],
 [87422250.0, 2941018.0, 87925000],
 [85087750.0, 2882545.0, 85575000],
 [85855000.0, 2941870.0, 85500000],
 [88944250.0, 3041045.0, 88875000],
 [89486250.0, 3032490.0, 90000000],
 [84769000.0, 2864132.0, 84925000],

While this may seem a little intimidating at first, we are only including 7 python statements inside this loop that we can run as many times as we want. On my standard laptop, I can run 1000 simulations in 2.75s so there is no reason I can’t do this many more times if need be.

At some point, there are diminishing returns. The results of 1 Million simulations are not necessarily any more useful than 10,000. My advice is to try different amounts and see how the output changes.

In order to analyze the results of the simulation, I will build a dataframe from all_stats :

In [13]:
results_df = pd.DataFrame.from_records(all_stats, columns=['Sales',
                                                           'Commission_Amount',
                                                           'Sales_Target'])
results_df

          Sales  Commission_Amount  Sales_Target
0    85470500.0          2977448.0      85025000
1    82852000.0          2909612.0      81600000
2    83843250.0          2872275.0      83350000
3    82774000.0          2858772.0      82625000
4    85466500.0          2931318.0      85075000
..          ...                ...           ...
995  87040750.0          2946008.0      87700000
996  79846500.0          2730485.0      79750000
997  83762500.0          2889580.0      83250000
998  83418500.0          2826305.0      83500000
999  84207250.0          2852338.0      84625000

[1000 rows x 3 columns]

Now, it is easy to see what the range of results look like:

In [74]:
results_df.describe().style.format('{:,}')

So, what does this chart and the output of describe tell us? We can see that the average commissions expense is $2.85M and the standard deviation is $103K. We can also see that the commissions payment can be as low as $2.5M or as high as $3.2M.

Based on these results, how comfortable are you that the expense for commissions will be less than $3M? Or, if someone says, “Let’s only budget $2.7M” would you feel comfortable that your expenses would be below that amount? Probably not.

Therein lies one of the benefits of the Monte Carlo simulation. You develop a better understanding of the distribution of likely outcomes and can use that knowledge plus your business acumen to make an informed estimate.

The other value of this model is that you can model many different assumptions and see what happens. Here are some simple changes you can make to see how the results change:

Increase top commission rate to 5%
Decrease the number of sales people
Change the expected standard deviation to a higher amount
Modify the distribution of targets
Now that the model is created, making these changes is as simple as a few variable tweaks and re-running your code. You can view the notebook associated with this post on github.

Another observation about Monte Carlo simulations is that they are relatively easy to explain to the end user of the prediction. The person receiving this estimate may not have a deep mathematical background but can intuitively understand what this simulation is doing and how to assess the likelihood of the range of potential results.

Finally, I think the approach shown here with python is easier to understand and replicate than some of the Excel solutions you may encounter. Because python is a programming language, there is a linear flow to the calculations which you can follow.

### Conclusion
A Monte Carlo simulation is a useful tool for predicting future results by calculating a formula multiple times with different random inputs. This is a process you can execute in Excel but it is not simple to do without some VBA or potentially expensive third party plugins. Using numpy and pandas to build a model and generate multiple potential results and analyze them is relatively straightforward. The other added benefit is that analysts can run many scenarios by changing the inputs and can move on to much more sophisticated models in the future if the needs arise. Finally, the results can be shared with non-technical users and facilitate discussions around the uncertainty of the final results.

I hope this example is useful to you and gives you ideas that you can apply to your own problems. Please feel free to leave a comment if you find this article helpful for developing your own estimation models.

Updates
19-March-2019: Based on comments from reddit, I have made another implementation which is faster: https://github.com/chris1610/pbpython/blob/master/notebooks/Monte_Carlo_Simulationv2.ipynb