In [21]:
import pandas as pd
 
# the types of data within the iris dataset
col_names = ["sepal_length", "sepal_width", "petal_length", "petal_width", "subspecies"]

pthX = r'C:\Users\hilton.netta\OneDrive - Prescient\py\gitrepo'
iris_data = pd.read_csv(pthX + r'\iris.csv', sep=',', header=None, names=col_names, index_col=None)

In [22]:
iris_data

     sepal_length  sepal_width  petal_length  petal_width subspecies
0    sepal.length  sepal.width  petal.length  petal.width    variety
1             5.1          3.5           1.4           .2     Setosa
2             4.9            3           1.4           .2     Setosa
3             4.7          3.2           1.3           .2     Setosa
4             4.6          3.1           1.5           .2     Setosa
..            ...          ...           ...          ...        ...
146           6.7            3           5.2          2.3  Virginica
147           6.3          2.5             5          1.9  Virginica
148           6.5            3           5.2            2  Virginica
149           6.2          3.4           5.4          2.3  Virginica
150           5.9            3           5.1          1.8  Virginica

[151 rows x 5 columns]

In [23]:
#%%
iris_setosa = iris_data[iris_data['subspecies']=='Iris-setosa']
iris_setosa = iris_setosa.drop(['subspecies'], axis=1)
 
iris_versicolor = iris_data[iris_data['subspecies']=='Iris-versicolor']
iris_versicolor=iris_versicolor.drop(['subspecies'], axis=1)
 
iris_virginica = iris_data[iris_data['subspecies']=='Iris-virginica']
iris_virginica=iris_virginica.drop(['subspecies'], axis=1)
 
#%%
mean_setosa = iris_setosa.mean(axis=0)
std_setosa = iris_setosa.std(axis=0)
 
mean_versicolor = iris_versicolor.mean(axis=0)
std_versicolor = iris_versicolor.std(axis=0)
 
mean_virginica = iris_virginica.mean(axis=0)
std_virginica = iris_virginica.std(axis=0)
 
subspecies = ['Setosa', 'Versicolor', 'Virginica']
 
mean_vals = pd.concat([mean_setosa, mean_versicolor, mean_virginica], axis=1)
mean_vals.columns=subspecies
 
std_vals = pd.concat([std_setosa, std_versicolor, std_virginica], axis=1)
std_vals.columns=subspecies

In [24]:
mean_setosa

sepal_length    NaN
sepal_width     NaN
petal_length    NaN
petal_width     NaN
dtype: object

In [25]:
mean_vals

             Setosa Versicolor Virginica
sepal_length    NaN        NaN       NaN
sepal_width     NaN        NaN       NaN
petal_length    NaN        NaN       NaN
petal_width     NaN        NaN       NaN

In [26]:
std_vals

             Setosa Versicolor Virginica
sepal_length    NaN        NaN       NaN
sepal_width     NaN        NaN       NaN
petal_length    NaN        NaN       NaN
petal_width     NaN        NaN       NaN

In [27]:
mean_vals.to_csv(pthX + r'\iris_means.csv', sep=',', header=True, index=True)
std_vals.to_csv( pthX + r'\iris_std.csv',   sep=',', header=True, index=True)